name: build analyze, scan
on:
  push:
    branches:
      - main

jobs:
  build-analyze-scan:
    name: build
    runs-on: ubuntu-latest

    steps:
      - name: checkout the code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: dependencies install
        run: npm install

      - name: trivy scan
        run: trivy fs .

      - name: docker build push
        run: |
          docker build -t zomato .
          docker tag zomato imarchit/zomato:latest
          echo ${{ secrets.DOCKERHUB_TOKEN }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
          docker push imarchit/zomato:latest
        env:
          DOCKER_CLI_ACL: 1

  deploy:
    name: deploy app to docker
    needs: build-analyze-scan
    runs-on: ubuntu-latest

    steps:
      - name: docker pull
        run: docker pull imarchit/zomato:latest

      - name: Image scan
        run: trivy image imarchit/zomato:latest > image-trivy-scan.txt

      - name: run docker container
        run: docker run -itd -p 3000:3000 imarchit/zomato:latest
