name: build analyze, scan
on:
  push:
    branches:
      - main

jobs:
  build-analyze-scan:
    name: build
    runs-on: ubuntu-latest

    steps:
      - name: checkout the code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: install Trivy
        run: |
          sudo apt-get update
          sudo apt-get install -y wget apt-transport-https gnupg lsb-release
          wget -qO - https://aquasecurity.github.io/trivy-repo/deb/public.key | sudo apt-key add -
          echo deb https://aquasecurity.github.io/trivy-repo/deb $(lsb_release -sc) main | sudo tee -a /etc/apt/sources.list.d/trivy.list
          sudo apt-get update
          sudo apt-get install -y trivy

      - name: dependencies install
        run: npm install

      - name: trivy scan
        run: trivy fs .

      - name: docker build push
        env:
          DOCKER_CLI_ACL: 1
        run: |
          docker build -t zomato .
          docker tag zomato imarchit/zomato:latest
          echo ${{ secrets.DOCKER_ACCESS_KEY }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
          docker push imarchit/zomato:latest

  deploy:
    name: deploy app to docker
    needs: build-analyze-scan
    runs-on: ubuntu-latest

    steps:
      - name: install Trivy
        run: |
          sudo apt-get update
          sudo apt-get install -y wget apt-transport-https gnupg lsb-release
          wget -qO - https://aquasecurity.github.io/trivy-repo/deb/public.key | sudo apt-key add -
          echo deb https://aquasecurity.github.io/trivy-repo/deb $(lsb_release -sc) main | sudo tee -a /etc/apt/sources.list.d/trivy.list
          sudo apt-get update
          sudo apt-get install -y trivy

      - name: docker pull
        run: docker pull imarchit/zomato:latest

      - name: Image scan
        run: trivy image imarchit/zomato:latest > image-trivy-scan.txt

      - name: run docker container
        run: docker run -itd -p 3000:3000 imarchit/zomato:latest
